AWSTemplateFormatVersion: "2010-09-09"
Description: "ADE_1.0 - VPC, Subnet, and Cloud9 Environment"
Parameters: 
  VpcCIDR: 
    Default: 10.16.0.0/16
    Description: "The CIDR block for the VPC"
    Type: String
    
  SubnetCIDR: 
    Default: 10.16.10.0/24
    Description: "CIDR for public subnet"
    Type: String

  KeyName: 
    Default: vockey
    Description: "Amazon EC2 Key Pair"
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true  
      Tags: 
        - Key: Name
          Value: "Lab VPC"

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: 
        Fn::Select:
          - 0
          - Fn::GetAZs: ''
      CidrBlock: !Ref SubnetCIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: "Lab subnet"
        
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: "Lab IGW"

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      VpcId: !Ref VPC
      InternetGatewayId: !Ref IGW

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: "Lab Route Table"

  Route:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref IGW

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet
      RouteTableId: !Ref RouteTable

  Cloud9Environment:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties: 
      InstanceType: t2.micro
      SubnetId: !Ref Subnet
      ImageId: amazonlinux-2-x86_64      
      Name: "Cloud9 Environment"
      AutomaticStopTimeMinutes: 30

Outputs:
  VPCID:
    Description: "VPC ID"
    Value: !Ref VPC

  SubnetID:
    Description: "Subnet ID"
    Value: !Ref Subnet

  IGWID:
    Description: "Internet Gateway ID"
    Value: !Ref IGW

  RouteTableID:
    Description: "Route Table ID"
    Value: !Ref RouteTable

  Cloud9EnvironmentID:
    Description: "Cloud9 Environment ID"
    Value: !Ref Cloud9Environment
